import { v4 as uuid } from "uuid";


export const products = [
  {
    _id: uuid(),
    name: "AZITHRAL",
    seller: "UNO PHARMA",
    price: 120,
    categoryName:"medicines",
    image:"https://admin.davagenie.com/assets/images/product/7110_1.png" ,
    rating: "3",
  },
  {
    _id: uuid(),
    title: "FABI-FLU",
    seller: "SPARSH PHARMA",
    price: 400,
    categoryName: "medicines",
    image:"https://www.netmeds.com/images/product-v1/600x600/921074/fabiflu_400_tablet_17s_0_0.jpg" ,
    rating: "4.5",
  },
  {
    _id: uuid(),
    title: "CORONIL",
    seller: "PTANJALI",
    price: 250,
    categoryName:"medicines",
    image:"https://n3.sdlcdn.com/imgs/j/k/n/Patanjali-Coronil-KIT-Tablet-1-SDL928674849-3-ad453.jpg" ,
    rating: "5",
  },
  {
    _id: uuid(),
    title: "ARM-SLING",
    seller: "ALIMED",
    price: 850,
    categoryName:"rehab",
    image:"https://m.media-amazon.com/images/I/61gT8MuftXL._SY679_.jpg" ,
    rating: "3.5",
  },
  {
    _id: uuid(),
    title: "WHEEL CHAIR",
    seller: "MEDI MART",
    price: 5000,
    categoryName:"rehab",
    image:"https://5.imimg.com/data5/TW/UB/MY-2224653/basic-wheelchair-red-500x500.jpg" ,
    rating: "4",
  },
  {
    _id: uuid(),
    title:"PULSE OXIMETER",
    seller:"MEDSURE",
    price: 1000,
    categoryName:"medtech",
    image:"https://n2.sdlcdn.com/imgs/j/r/2/db-enbloc-PULSE-OXIMETER-MAKE-SDL217883061-1-815e3.jpg",
    rating: "2",
  },
  {
    _id: uuid(),
    title: "SPHYGMOMANO METER",
    seller: "MEDSURE",
    price: 3000,
    categoryName:"medtech",
    image:"https://sc02.alicdn.com/kf/H6edae661e80e462da395b6466de997b8o/230093207/H6edae661e80e462da395b6466de997b8o.jpg_.webp" ,
    rating: "4",
  },
  // {
  //   _id: uuid(),
  //   title: "SYRINGE",
  //   seller: "G.S.K",
  //   price: 50,
  //   categoryName: "Med-Tech",
  //   image:"https://5.imimg.com/data5/SELLER/Default/2021/6/MQ/SY/TI/21284661/syringe-with-needle-2ml-22g-23g-24g-500x500.jpg" ,
  // },

];
